#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

if test "$(uname -s)" = "Darwin"; then
  ./homebrew/install.sh
else
  ./apt-get/install.sh
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
