alias reload!='. ~/.zshrc'
alias vim='nvim'
alias y='yarn'
alias yg='yarn global'
alias subl='open -a "Sublime Text"'
alias stree='/Applications/SourceTree.app/Contents/Resources/stree'
alias ta='tmux attach'
alias tlocal='tmux attach-session -t local || tmux new-session -s local'
